# ShelfWise Azure OpenAI Provisioner
# Run this in PowerShell to create Azure OpenAI and auto-configure ShelfWise
# Requires: Azure CLI installed and logged in (az login)

param(
    [string]$ResourceGroupName = "shelfwise-hackathon-rg",
    [string]$Location = "eastus",
    [string]$ResourcePrefix = "shelfwise",
    [string]$ModelName = "gpt-4.1-mini"
)

$ErrorActionPreference = "Stop"
$OpenAIName = "$ResourcePrefix-openai"
$DeploymentName = $ModelName

function Write-Info($msg) { Write-Host "[INFO] $msg" -ForegroundColor Cyan }
function Write-Success($msg) { Write-Host "[OK] $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "[WARN] $msg" -ForegroundColor Yellow }

# Check Azure CLI
Write-Info "Checking Azure CLI..."
$azVersion = az --version 2>$null | Select-String "azure-cli"
if (-not $azVersion) {
    Write-Error "Azure CLI not found. Install: winget install Microsoft.AzureCLI"
    exit 1
}
Write-Success "Azure CLI found"

# Check login
Write-Info "Checking Azure login..."
$account = az account show --query "name" -o tsv 2>$null
if (-not $account) {
    Write-Error "Not logged in. Run: az login"
    exit 1
}
Write-Success "Logged in as: $account"

# Create resource group
Write-Info "Creating resource group: $ResourceGroupName in $Location..."
$rgExists = az group exists --name $ResourceGroupName --query "name" -o tsv 2>$null
if (-not $rgExists) {
    az group create --name $ResourceGroupName --location $Location | Out-Null
    Write-Success "Resource group created"
} else {
    Write-Warn "Resource group already exists"
}

# Create Azure OpenAI
Write-Info "Creating Azure OpenAI: $OpenAIName..."
$existingOpenAI = az cognitiveservices account show `
    --name $OpenAIName `
    --resource-group $ResourceGroupName `
    --query "name" -o tsv 2>$null

if (-not $existingOpenAI) {
    az cognitiveservices account create `
        --name $OpenAIName `
        --resource-group $ResourceGroupName `
        --location $Location `
        --kind OpenAI `
        --sku S0 `
        --custom-domain $OpenAIName `
        --yes | Out-Null
    Write-Success "Azure OpenAI resource created"
} else {
    Write-Warn "Azure OpenAI already exists"
}

# Get endpoint
$Endpoint = az cognitiveservices account show `
    --name $OpenAIName `
    --resource-group $ResourceGroupName `
    --query "properties.endpoint" -o tsv
Write-Success "Endpoint: $Endpoint"

# Deploy model
Write-Info "Deploying model: $ModelName..."
$existingDeployment = az cognitiveservices account deployment show `
    --name $OpenAIName `
    --resource-group $ResourceGroupName `
    --deployment-name $DeploymentName `
    --query "name" -o tsv 2>$null

if (-not $existingDeployment) {
    # Get latest version
    $ModelVersion = az cognitiveservices account list-models `
        --name $OpenAIName `
        --resource-group $ResourceGroupName `
        --query "[?name=='$ModelName'].version | sort(@) | [-1]" -o tsv 2>$null

    if (-not $ModelVersion) {
        $ModelVersion = "2024-11-20"
        Write-Warn "Could not query version, using fallback: $ModelVersion"
    }

    az cognitiveservices account deployment create `
        --name $OpenAIName `
        --resource-group $ResourceGroupName `
        --deployment-name $DeploymentName `
        --model-name $ModelName `
        --model-version $ModelVersion `
        --model-format OpenAI `
        --sku-name Standard `
        --sku-capacity 10 | Out-Null
    Write-Success "Model deployed: $DeploymentName (v$ModelVersion)"
} else {
    Write-Warn "Model deployment already exists"
}

# Get API key
Write-Info "Retrieving API key..."
$ApiKey = az cognitiveservices account keys list `
    --name $OpenAIName `
    --resource-group $ResourceGroupName `
    --query "key1" -o tsv
Write-Success "API key retrieved"

# Build .env content
$ApiVersion = "2024-02-01"
$FullEndpoint = "$Endpoint/openai/deployments/$DeploymentName/chat/completions?api-version=$ApiVersion"

$EnvContent = @"
# ShelfWise Environment Configuration
# Generated by setup-azure-openai.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Microsoft Foundry / Azure OpenAI Settings
FOUNDRY_ENDPOINT=$FullEndpoint
FOUNDRY_API_KEY=$ApiKey
FOUNDRY_MODEL=$ModelName

# Azure Resource Info (for reference)
AZURE_OPENAI_RESOURCE=$OpenAIName
AZURE_OPENAI_ENDPOINT=$Endpoint
AZURE_OPENAI_DEPLOYMENT=$DeploymentName
AZURE_RESOURCE_GROUP=$ResourceGroupName
"@

# Write .env file
$EnvPath = Join-Path $PSScriptRoot ".env"
$EnvContent | Set-Content -Path $EnvPath -Encoding UTF8
Write-Success ".env file written to: $EnvPath"

# Summary
Write-Host "`n========================================" -ForegroundColor Green
Write-Host "  AZURE OPENAI PROVISIONED" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host "Resource Group:  $ResourceGroupName" -ForegroundColor White
Write-Host "OpenAI Resource: $OpenAIName" -ForegroundColor White
Write-Host "Deployment:      $DeploymentName" -ForegroundColor White
Write-Host "Endpoint:        $Endpoint" -ForegroundColor White
Write-Host "API Key:         $($ApiKey.Substring(0,8))..." -ForegroundColor White
Write-Host "`n.env file saved. Restart ShelfWise to use live Foundry reasoning." -ForegroundColor Cyan
Write-Host "`nTo delete resources later:" -ForegroundColor Gray
Write-Host "  az group delete --name $ResourceGroupName --yes" -ForegroundColor Gray
